// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iohbechgxyplxlozsmcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvaGJlY2hneHlwbHhsb3pzbWNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY3NDY0OTYsImV4cCI6MjA4MjMyMjQ5Nn0.1ra-JCATkLUBG-gVH67vY5gJSFs-IU2dSJHXvdtnBko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});